config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "dashboard" => "dashboard#view"

  resources :activities do
    member do
      get 'close'
      get 'open'
    end

    collection do 
      get "pending"
      get "closed"
      get "search"
    end
  end
  

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  include Activity::Constants

  belongs_to :category
  
  default_scope { order('created_at DESC') }
  scope :created_after, ->(time) { where("created_at > ?", time) }
  scope :current, -> { where("status in ? or status is null", [ACTIVITY_STATUS[:open], ACTIVITY_STATUS[:pending]]) }
  scope :pending, -> { where("status in ?", ACTIVITY_STATUS[:pending]) }
  scope :not_categorized, -> { where("category_id is null") }
  scope :get_by_priority, ->(type) { where("priority = ?", type)}

  validates :content, :presence => true

  def closed?
    self.status == "close"
  end

  def self.fetch_by_priority_type(type)
    return unless ACTIVITY_PRIORITIES.keys.include?(type)
    # priority matters only in the open/pending items
    Activity.pending.get_by_priority(type)
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :activities, inverse_of: :category

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  include Activity::Constants

	def index
    @activities = Activity.all
    @item = Activity.new
	end

  def new
    @item = Activity.new    
  end

  def edit
    @activity = Activity.find_by_id(params[:id])
  end

  def create
    activity = Activity.new(activity_params)
    activity.update_attributes(:status => "open")
    if activity.save
      flash['success'] = "Activity created sucessfully"
      redirect_to activities_path
    else
      flash['danger'] = "Activity creation failed"
      redirect_to :back
    end
  end

  def update
    activity = Activity.find_by_id(params[:id])
    activity.update_attributes(:content => params[:activity][:content])
    if activity.save!
      flash['success'] = "Activity updated sucessfully"
      redirect_to activities_path
    else
      flash['danger'] = "Activity creation failed"
      redirect_to edit_activity_url(params[:id])
    end
  end

  def show
    @activity = Activity.find_by_id(params[:id])
  end

  def close
    activity = Activity.find_by_id(params[:id])
    if activity.present?
      activity.update_attributes(:status => "close")
      if activity.save!
        flash['success'] = "Activity updated"
      else
        flash['error'] = "Activity update failed"
      end
    else
      flash['danger'] = "No activity present"
    end
    redirect_to activities_path
  end

  def pending
    @activities = Activity.all.pending
  end

  def open
    activity = Activity.find_by_id(params[:id])
    if activity.present?
      activity.update_attributes(:status => ACTIVITY_STATUS[:open])
      if activity.save!
        flash['success'] = "Activity updated"
      else
        flash['error'] = "Activity update failed"
      end
    else
      flash['danger'] = "No activity present"
    end
    redirect_to activities_path
  end

  def search
    
  end

  private
    def activity_params
      params.require(:activity).permit(:content)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def view
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/activities/_activity_form.html.erb
<%= render "new_activity_form" %>

<div class="row">
  <% if @activities.empty? %>
    <div class="app-private">No activities present</div>
  <% else %>
    <% index = 0 %>
    <% @activities.group_by{|e| e.created_at.to_date}.each do |c_date, activity_arr| %>
        <h4 class="activity_header"> 
          <a class="btn" data-toggle="collapse" data-target='<%= "#date-#{index}" %>' > 
            <%= Activity::DateFormater.format_time(c_date) %> 
          </a>
        </h4>
        <div class="container collapse in" id='<%= "date-#{index}" %>' >
          <% activity_arr.each do |activity| %>
            <% if false %>
              <div class="btn-group">
                  <% if !activity.closed? %>
                    <%= link_to "Close", close_activity_url(activity), :class => "btn btn-primary app-private" %> 
                  <% end %>
                  <% if activity.closed? %>
                    <%= link_to "Open", open_activity_url(activity), :class => "btn btn-primary app-private" %>
                  <% end %>
                <%= link_to "Edit", edit_activity_url(activity), :class => "btn btn-primary app-private" %>
              </div>
            <% end %>
            <div class="well activity_item draggable-element col-sm-3 col-md-3 col-lg-3">
              <span class="activity_buttons"> 
                <a class="activity_button" href=<%= edit_activity_url(activity) %>> <%= image_tag "activity_edit.png" %> </a>
              </span>
              <%= hidden_field(:activity, :priority, :value => activity.priority) %>
              <%= hidden_field(:activity, :created_at, :value => activity.created_at.to_date) %>
              <p>
              <%= simple_format(h activity.content.to_s) %>
              </p>
              <i>
                <% if false %>
                  <%= "created #{Time.parse(activity.created_at.inspect).httpdate}" %>
                <% end %>
              </i>
            </div>
          <% end %>
        </div>
      <% index = index + 1 %>
    <% end %>
  <% end %>
</div>

app/views/activities/_new_activity_form.html.erb
<a class="btn" data-toggle="collapse" data-target="#new_activity_form">
  <%= image_tag "activity_add.png" %>
</a>

<a class="btn" data-toggle="collapse" data-target="#activity_search_bar">
  <%= image_tag "activity_search.png" %>
</a>

<div class="container collapse" id="activity_search_bar">
  <p>
    <form name="search_form" method="get" action="/activities/search" target="_self">
      <input id="activity_search" type="text" name="activity_search" size="40"/>
    </form>
  </p>
</div>

<% if @item.present? %>
  <div class="row">
    <div class="container collapse in" id='new_activity_form'>
      <div class="col-md-6">
        <p>
        <%= form_for(@item) do |a| %>
          <%= a.label "Please enter task to track!", class: 'app-white' %>
          <%= a.text_area :content, class: 'form-control', rows: "3" %>
          <br>
          <p>
            <%= a.label :status, :class => "app-white" %>
            <%= select_tag(:status, options_for_select(Activity::Constants::ACTIVITY_STATUS.map{|k,v| [k, v]}, 1)) %>
          </p>
          
          <p>
            <%= a.label :priority, :class => "app-white" %>
            <%= select_tag(:priority, options_for_select((-15..10).map{|e| [e, e]}, 1)) %>
          </p>
          <%= a.submit "Submit", class: 'btn btn-primary app-private app-button' %>
        <% end %>
        </p>
      </div>
    </div>
  </div>
  <br>
<% end %>

app/views/activities/edit.html.erb
<h1 class="page-header app-white">Quick edit</h1>
<div class="row">
  <div class="col-md-6">
    <%= form_for(@activity) do |a| %>
      <p>
        <%= a.label :content, :class => "app-white" %>
        <%= a.text_area :content, class: 'form-control', rows: 7 %>
      </p>

      <p>
        <%= a.label :status, :class => "app-white" %>
        <%= select_tag(:status, options_for_select(Activity::Constants::ACTIVITY_STATUS.map{|k,v| [k, v]}, (@activity.status || 1))) %>
      </p>
      
      <p>
        <%= a.label :priority, :class => "app-white" %>
        <%= select_tag(:priority, options_for_select((-15..10).map{|e| [e, e]}, (@activity.priority || 17))) %>
      </p>

      <%= a.submit "Update", class: 'btn btn-primary app-private' %>
    <% end %>
  </div>
</div>

app/views/activities/index.html.erb
<%= render "activities/activity_form" %>


<!--   <div class='btn-toolbar pull-right'>  
    <div class='btn-group'>
        
        <button type='button' class='btn btn-primary'>Relate</button>
    </div>
  </div> -->

app/views/activities/new.html.erb
<%= render "new_activity_form" %>

app/views/activities/pending.html.erb
<h1>Pending items</h1>
<%= render "activities/activity_form" %>

app/views/dashboard/view.html.erb
<div class="row">
  <div class="col-sm-3 col-md-2 col-lg-2">
    <ul class="nav nav-sidebar">
      <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
      <li><a href="#">Export</a></li>
      <li><%= link_to "Closed Activities", closed_activities_url %></li>
      <li><%= link_to "Pending Activities", pending_activities_url %></li>
    </ul>
  </div>
  <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 col-lg-10 col-lg-offset-2 main">
    <h1 class="page-header app-white">Sign Board</h1>
    <div class="row placeholders">
      <div class="col-xs-6 col-sm-3 placeholder">
        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
        <h4>Open</h4>
      </div>
      <div class="col-xs-6 col-sm-3 placeholder">
        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
        <h4>Pending</h4>
      </div>
      <div class="col-xs-6 col-sm-3 placeholder">
        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
        <h4>Closed</h4>
      </div>
      <div class="col-xs-6 col-sm-3 placeholder">
        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
        <h4>Unassigned</h4>
      </div>
    </div>
  </div>
  <div style="display: block; clear: both;"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Personal Watcher</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Minion</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", dashboard_path %></li>
            <li><a href="#about">Request Feature</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Options <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">View activities by month</a></li>
                <li><a href="#">View activities by week</a></li>
                <li><a href="#">Usage Stats</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Bot Configuration</li>
                <li><a href="#">Settings</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Activity <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "New", new_activity_path %></li>
                <li><%= link_to "All", activities_path %></li>
                <li><%= link_to "Pending", pending_activities_path %></li>              
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container theme-showcase" id="app-body" role="main">
      <div class="page-header" style="visibility: hidden;">We understand you</div>
      <% if flash.any? %>
        <% flash.each do |key, value| %>
          <div class='<%="alert alert-#{key} app-private"%>' role="alert"><%= value %></div>
        <% end %>
      <% end %>
      <%= yield %>
<!--       <div id="activityDialog"><div id="activityDialogText"></div></div> -->
    </div>
  </body>
</html>

        